with import <nixpkgs> {}; [
    bat
    curl
    fontconfig
    fzf
    gcc
    git
    jq
    lua-language-server
    neovim
    nodePackages.bash-language-server
    pyright
    python310Full
    python310Packages.flake8
    python310Packages.ipython
    python310Packages.pipx
    python310Packages.virtualenv
    python310Packages.virtualenvwrapper
    ripgrep
    ruff
    terraform-ls
    tig
    tmux
    tree-sitter
    unzip
    wget
]
