#!/bin/bash

pid=$1
pane=$(ps eww ${pid}|tr ' ' '\n'|awk -F= '/TMUX_PANE/{print $2}')
if [ -z ${pane} ] ; then
    tmux display-message "PID ${pid} does not exist on this machine"
else
    tmux switch-client -t ${pane}
fi
