base_packages_all=(curl xz-utils)
minimal_scripts=(nvim.sh)
virtualenv_dir="${HOME}/.venvs"
binaries_dir="${HOME}/Binaries"
bin_dir="${HOME}/Binaries/bin"
localrc="${HOME}/.localrc"
create_dirs=("$virtualenv_dir" "$bin_dir")
tmux_plugins=(https://github.com/tmux-plugins/tpm)
go_url="https://storage.googleapis.com/golang"
fonts_expect=(RobotoMonoNerdFont-Regular.ttf)
fonts_dl=(https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/RobotoMono.zip)
zsh_extras=(https://github.com/zsh-users/zsh-autosuggestions https://github.com/zsh-users/zsh-syntax-highlighting https://github.com/romkatv/powerlevel10k)
